### PR TITLE
uniformized framework paths

### PR DESCRIPTION
**Pull request by rvdb**
This probably makes sense for https://github.com/TEIC/oxygen-tei/blob/master/oxygen-tei/frameworks/tei/teip5.framework and https://github.com/TEIC/oxygen-tei/blob/master/oxygen-tei/frameworks/tei/teip5odd.framework as well.

### CODE REVIEW

**Comment by raducoravu** [comment]
Could you explain why you propose this change? "${framework}" and "${frameworkDir}" without any document type name specified always point to the current framework folder. So it's more flexible not to specify the name of the framework if you make references inside the same framework.
Also you should not replace tokens like "${frameworkDir}" with "${framework(TEI P5)}", it should be replaced with ""${frameworkDir(TEI P5)}"". That "Dir" part means that it gets expanded as a file path and not as an URL path and this matters to Oxygen.

**Comment by rvdb** [comment]
@raducoravu I tried to address reports by @martindholmes about CSS files not being found for the "bleeding edge" add-on TEI framework, that specified the path as `${framework}/xml/tei/css/`.

Concerning `${framework}` vs `${frameworkDir}`: I was under the assumption that a URL would be more robust when it comes to differences in path separators in different operating systems. I tested locally, and it worked.

Thanks for your correction, but I'm confused: the [documentation](https://www.oxygenxml.com/doc/versions/20.0/ug-editor/topics/editor-variables.html) says that:

> **${frameworkDir}** - The path (as file path) of the current framework, as part of the [OXYGEN_INSTALL_DIR]/frameworks directory.
> **${frameworkDir(fr_name)}** - The path (as file path) of the fr_name framework.

Further, the documentation explains path resolution priorities, only for `${framework(fr_name)}` and `${frameworkDir(fr_name)}` .

This made me assume that `${frameworkDir}` would always point to the built-in TEI framework shipped with Oxygen, and that `${frameworkDir(fr_name)}` would be the only way to point to either the add-on framework, or the built-in framework. 

Could you please clarify?

**Comment by raducoravu** [comment]
I will add a documentation task on our side to remove that "as part of the [OXYGEN_INSTALL_DIR]/frameworks directory" part from the docs because it is incorrect.
So you should use "${framework(fr_name)}" or "${frameworkDir(fr_name)}" mostly when making references to resources from one framework to another or from a global transformation scenario which references a certain XSLT from a certain framework.

About:

            Concerning ${framework} vs ${frameworkDir}: I was under the assumption that a URL would be more robust when it comes to differences in path separators in different operating systems. I tested locally, and it worked.


So if the framework resides on the local disk in "c:\some\path\test.framework", when necessary the  "${framework}" will be expanded to "file:/c:/some/path/test.framework" and the "${frameworkDir}" will expand to "c:\some\path\test.framework".
In most places Oxygen uses only URLs so most of the times the "{framework}" is used but in certain places (like when specifying directories for new file templates at framework level) Oxygen wants those references to extra folder templates to expand to local folder paths because it cannot load new file templates from remote located folders.

If you give me some steps to reproduce the current problem on my side I could try to give you a more detailed answer.

**Comment by rvdb** [comment]
Ah, ok, that makes sense (again :-)). So this PR can be ignored.

Unfortunately, I'll have to refer to @martindholmes, since I haven't been able to reproduce the issue reported on my Windows-7 Oxygen-20.0 configuration. When I've been trying to reproduce it, I _seemed_ to hit a "CSS file not found" error briefly when creating a new jTEI article in Author mode, but after opening an existing jTEI article, which rendered fine, I haven't been able to reproduce it. This made me think some of some kind of caching issue, but hopefully Martin can be more precise.

**Comment by martindholmes** [comment]
@raducoravu @rvdb I'm working with the latest Oxygen, and the "bleeding edge" build of the TEI framework, which you can install using this file:

http://teijenkins.hcmc.uvic.ca/job/oxygen-tei-bleeding/lastSuccessfulBuild/artifact/oxygen-tei/updateSite.oxygen

I'm on Ubuntu 17.10. The problem I'm seeing is that nothing in the jTEI framework seems to work out of the box at all. If I create a "New" jTEI article, the resulting file does not find the Author mode CSS, and the two jTEI transformations (ODT and PDF) are not available for it. If this is only the case on Linux I'd be surprised; I suspect it's more likely that it only works on Windows for some path-related reason, and fails on *NIX OSes, but I haven't tested on Mac.

The bleeding edge version of the plugin is what we use for testing changes in the TEI and TEI Stylesheets repos to make sure that they haven't broken the Oxygen package, so I run with this plugin all the time so that I notice problems. I'm the canary in the coalmine in this respect. :-)

**Comment by martindholmes** [comment]
I've tested on another machine and can't reproduce the problem, so my guess is that it's some kind of interaction between project settings and the plugin settings. Probably my fault, so I'll close this. Apologies.

**Pull request closed without merging**
