### PR TITLE
added logback configuration file, in order to have PDF output warning…

### PR DESCRIPTION
**Pull request by rvdb**
…s (especially missing glyphs) properly reported

### CODE REVIEW

**Comment by DunaMariusCosmin** [comment]
Hi!

I think we should keep the same root level (warn) as in the old log4j configuration file: https://github.com/TEIC/oxygen-tei/blob/master/oxygen-tei/frameworks/tei/xml/tei/jtei_aux/trans/log4j2.properties
Also, the pattern from the ConsoleAppender should be preserved: 
```
<configuration>
    <appender name="R" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%r %p [ %t ] %c - %m%n</pattern>
        </encoder>
    </appender>

    <!-- TRACE < DEBUG < INFO < WARN < ERROR < OFF  -->
    <root level="warn">
        <appender-ref ref="R" />
    </root>
</configuration>
```
Could you check if this simplest form works properly?
Regards,
Cosmin

**Comment by rvdb** [comment]
Hi @DunaMariusCosmin , thanks for chiming in! For my commit, I'd just started from the default Oxygen logback.xml config file, and tweaked in an appender for the the WARN level. Just to make it work, without much knowledge of logback, or other considerations in mind.

So, totally happy to use your version, which seems to work fine! I'm a notorious Git disaster; if I should just update the file and commit to the same branch in my repo, that's something I should be able to manage. Otherwise, don't hesitate to tell me how to proceed exactly.

**Comment by DunaMariusCosmin** [comment]
Thank you for checking the file. 
Committing on the same branch should also apply to this pull request. So, it would be perfect if you could commit the updated configuration file.

**Comment by rvdb** [comment]
Ok, done.

**Pull request merged**
