### PR TITLE
added unifont as fallback font for unsupported characters

### PR DESCRIPTION
**Pull request by rvdb**

### CODE REVIEW

**Comment by georgebina** [comment]
Unfortunately this has a GPL license so it will force the oxygen-tei framework license also to GPL and then we will not be able to distribute the framework automatically with oXygen.  
I propose to revert this change or find another way of licensing that font to be able to keep the original project license.

Regards,
George

**Comment by rvdb** [comment]
Ouch, that's a pity, my apologies. I assumed the license would only affect the use of the font, not the entire project in which it is distributed. Are there any problems with any of the other font licenses at https://github.com/TEIC/oxygen-tei/tree/master/oxygen-tei/frameworks/tei/xml/tei/jtei_aux/trans/pdf/fonts-license?

I've been considering a [Google Noto](https://www.google.com/get/noto/) font as a possible alternative; does their [SIL Open Font license](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) pose any problems? Apart from that, their fragmentation into 217 different fonts will make it much harder to select the right font (of course, there's no limit on the exotic character jTEI articles can possibly contain), and I can imagine including their 500Mb in the oxygen-tei-framework will be overkill for the rare occasions they will actually be used. If you happen to have any ideas, that would be welcome...

Best, 

Ron

**Comment by georgebina** [comment]
The other licenses are ok, they are public domain, SIL OFL 1.1 and Apache 2.0.

**Comment by rvdb** [comment]
Ok, thanks. So Google Noto (SIL OFL) is a possible alternative, license-wise.

**Comment by rvdb** [comment]
Hi @georgebina , if we included an instruction in the Ant script driving the PDF transformation to download the unifont font (and probably the license text file, too) when necessary (and if it isn't already present on the user's system), would that be compatible with the oxygen-tei framework?

**Comment by georgebina** [comment]
Instructions for users to download and use GPL-licensed fonts should be fine from a licensing point if view.

**Comment by martindholmes** [comment]
@georgebina I think the idea would be to download required fonts automatically as part of the conversion process.

**Comment by georgebina** [comment]
I am afraid that is not ok. In this way any non GPL project can include GPL content by downloading it when it is needed.

**Comment by martindholmes** [comment]
I see the problem. It looks like we could do this outside of Oxygen but not in the actual plugin.

**Comment by rvdb** [comment]
Ok, meanwhile we're thinking of the Google Noto font family as a more complete solution for exotic character support. As you've pointed out in https://github.com/TEIC/oxygen-tei/pull/20#issuecomment-321263553, its SIL OFL is usable within the oxygen-tei framework.

Since it wouldn't be desirable to include the entire Google Noto font collection into the oxygen-tei framework, we're considering a similar approach as pointed out earlier, viz. to automatically download required fonts on demand. But I assume that as long as the license is compatible, the principle of downloading extra fonts is not an issue.

**Comment by georgebina** [comment]
Yes, it should be fine to download the Noto font collection as needed.

**Pull request merged**
